// Generated by ts-to-zod
import { z } from "zod";

const nodeSchema = z.any();

const edgeSchema = z.any();

const builderNodeTypeSchema = z.any();

const tagSchema = z.any();

const stateSchema = z.object({
  nodes: z.array(nodeSchema),
  edges: z.array(edgeSchema),
  sidebar: z.object({
    active: z.union([
      z.literal("node-properties"),
      z.literal("available-nodes"),
      z.literal("none"),
      z.string(),
    ]),
    panels: z.object({
      nodeProperties: z.object({
        selectedNode: z
          .union([
            z.object({
              id: z.string(),
              type: builderNodeTypeSchema,
            }),
            z.undefined(),
          ])
          .nullable(),
      }),
    }),
  }),
});
